name: binf_educational_app_redone
description: "A Bioinformatics Educational Mobile Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.5
  uuid: ^4.5.3
  sqflite: ^2.4.2+1
  webview_flutter: ^4.14.1
  carousel_slider: ^5.1.2
  flutter_3d_controller: ^2.3.0
  http: ^1.6.0
  device_info_plus: ^13.2.0
  provider: ^6.1.5+1

  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3

  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  path_provider: ^2.1.6

  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.15.1

  freezed: ^3.2.5
  json_serializable: ^6.14.0
  isar_community_generator: ^3.3.2

  mocktail: ^1.0.5
 
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/molecules/
    - assets/data/